// File generated from our OpenAPI spec by Stainless.

package com.dodopayments.api.models.payments

import com.dodopayments.api.core.JsonValue
import com.dodopayments.api.core.jsonMapper
import com.dodopayments.api.models.disputes.Dispute
import com.dodopayments.api.models.disputes.DisputeStage
import com.dodopayments.api.models.disputes.DisputeStatus
import com.dodopayments.api.models.misc.CountryCode
import com.dodopayments.api.models.misc.Currency
import com.dodopayments.api.models.refunds.Refund
import com.dodopayments.api.models.refunds.RefundStatus
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class PaymentTest {

    @Test
    fun create() {
        val payment =
            Payment.builder()
                .billing(
                    BillingAddress.builder()
                        .city("city")
                        .country(CountryCode.AF)
                        .state("state")
                        .street("street")
                        .zipcode("zipcode")
                        .build()
                )
                .brandId("brand_id")
                .businessId("business_id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .currency(Currency.AED)
                .customer(
                    CustomerLimitedDetails.builder()
                        .customerId("customer_id")
                        .email("email")
                        .name("name")
                        .build()
                )
                .addDispute(
                    Dispute.builder()
                        .amount("amount")
                        .businessId("business_id")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .currency("currency")
                        .disputeId("dispute_id")
                        .disputeStage(DisputeStage.PRE_DISPUTE)
                        .disputeStatus(DisputeStatus.DISPUTE_OPENED)
                        .paymentId("payment_id")
                        .remarks("remarks")
                        .build()
                )
                .metadata(
                    Payment.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .paymentId("payment_id")
                .addRefund(
                    Refund.builder()
                        .businessId("business_id")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .isPartial(true)
                        .paymentId("payment_id")
                        .refundId("refund_id")
                        .status(RefundStatus.SUCCEEDED)
                        .amount(0)
                        .currency(Currency.AED)
                        .reason("reason")
                        .build()
                )
                .settlementAmount(0)
                .settlementCurrency(Currency.AED)
                .totalAmount(0)
                .cardIssuingCountry(CountryCode.AF)
                .cardLastFour("card_last_four")
                .cardNetwork("card_network")
                .cardType("card_type")
                .discountId("discount_id")
                .errorCode("error_code")
                .errorMessage("error_message")
                .paymentLink("payment_link")
                .paymentMethod("payment_method")
                .paymentMethodType("payment_method_type")
                .addProductCart(
                    Payment.ProductCart.builder().productId("product_id").quantity(0).build()
                )
                .settlementTax(0)
                .status(IntentStatus.SUCCEEDED)
                .subscriptionId("subscription_id")
                .tax(0)
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .build()

        assertThat(payment.billing())
            .isEqualTo(
                BillingAddress.builder()
                    .city("city")
                    .country(CountryCode.AF)
                    .state("state")
                    .street("street")
                    .zipcode("zipcode")
                    .build()
            )
        assertThat(payment.brandId()).isEqualTo("brand_id")
        assertThat(payment.businessId()).isEqualTo("business_id")
        assertThat(payment.createdAt()).isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(payment.currency()).isEqualTo(Currency.AED)
        assertThat(payment.customer())
            .isEqualTo(
                CustomerLimitedDetails.builder()
                    .customerId("customer_id")
                    .email("email")
                    .name("name")
                    .build()
            )
        assertThat(payment.disputes())
            .containsExactly(
                Dispute.builder()
                    .amount("amount")
                    .businessId("business_id")
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .currency("currency")
                    .disputeId("dispute_id")
                    .disputeStage(DisputeStage.PRE_DISPUTE)
                    .disputeStatus(DisputeStatus.DISPUTE_OPENED)
                    .paymentId("payment_id")
                    .remarks("remarks")
                    .build()
            )
        assertThat(payment.metadata())
            .isEqualTo(
                Payment.Metadata.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(payment.paymentId()).isEqualTo("payment_id")
        assertThat(payment.refunds())
            .containsExactly(
                Refund.builder()
                    .businessId("business_id")
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .isPartial(true)
                    .paymentId("payment_id")
                    .refundId("refund_id")
                    .status(RefundStatus.SUCCEEDED)
                    .amount(0)
                    .currency(Currency.AED)
                    .reason("reason")
                    .build()
            )
        assertThat(payment.settlementAmount()).isEqualTo(0)
        assertThat(payment.settlementCurrency()).isEqualTo(Currency.AED)
        assertThat(payment.totalAmount()).isEqualTo(0)
        assertThat(payment.cardIssuingCountry()).isEqualTo(CountryCode.AF)
        assertThat(payment.cardLastFour()).isEqualTo("card_last_four")
        assertThat(payment.cardNetwork()).isEqualTo("card_network")
        assertThat(payment.cardType()).isEqualTo("card_type")
        assertThat(payment.discountId()).isEqualTo("discount_id")
        assertThat(payment.errorCode()).isEqualTo("error_code")
        assertThat(payment.errorMessage()).isEqualTo("error_message")
        assertThat(payment.paymentLink()).isEqualTo("payment_link")
        assertThat(payment.paymentMethod()).isEqualTo("payment_method")
        assertThat(payment.paymentMethodType()).isEqualTo("payment_method_type")
        assertThat(payment.productCart())
            .containsExactly(
                Payment.ProductCart.builder().productId("product_id").quantity(0).build()
            )
        assertThat(payment.settlementTax()).isEqualTo(0)
        assertThat(payment.status()).isEqualTo(IntentStatus.SUCCEEDED)
        assertThat(payment.subscriptionId()).isEqualTo("subscription_id")
        assertThat(payment.tax()).isEqualTo(0)
        assertThat(payment.updatedAt()).isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val payment =
            Payment.builder()
                .billing(
                    BillingAddress.builder()
                        .city("city")
                        .country(CountryCode.AF)
                        .state("state")
                        .street("street")
                        .zipcode("zipcode")
                        .build()
                )
                .brandId("brand_id")
                .businessId("business_id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .currency(Currency.AED)
                .customer(
                    CustomerLimitedDetails.builder()
                        .customerId("customer_id")
                        .email("email")
                        .name("name")
                        .build()
                )
                .addDispute(
                    Dispute.builder()
                        .amount("amount")
                        .businessId("business_id")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .currency("currency")
                        .disputeId("dispute_id")
                        .disputeStage(DisputeStage.PRE_DISPUTE)
                        .disputeStatus(DisputeStatus.DISPUTE_OPENED)
                        .paymentId("payment_id")
                        .remarks("remarks")
                        .build()
                )
                .metadata(
                    Payment.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .paymentId("payment_id")
                .addRefund(
                    Refund.builder()
                        .businessId("business_id")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .isPartial(true)
                        .paymentId("payment_id")
                        .refundId("refund_id")
                        .status(RefundStatus.SUCCEEDED)
                        .amount(0)
                        .currency(Currency.AED)
                        .reason("reason")
                        .build()
                )
                .settlementAmount(0)
                .settlementCurrency(Currency.AED)
                .totalAmount(0)
                .cardIssuingCountry(CountryCode.AF)
                .cardLastFour("card_last_four")
                .cardNetwork("card_network")
                .cardType("card_type")
                .discountId("discount_id")
                .errorCode("error_code")
                .errorMessage("error_message")
                .paymentLink("payment_link")
                .paymentMethod("payment_method")
                .paymentMethodType("payment_method_type")
                .addProductCart(
                    Payment.ProductCart.builder().productId("product_id").quantity(0).build()
                )
                .settlementTax(0)
                .status(IntentStatus.SUCCEEDED)
                .subscriptionId("subscription_id")
                .tax(0)
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .build()

        val roundtrippedPayment =
            jsonMapper.readValue(jsonMapper.writeValueAsString(payment), jacksonTypeRef<Payment>())

        assertThat(roundtrippedPayment).isEqualTo(payment)
    }
}
