// File generated from our OpenAPI spec by Stainless.

package com.dodopayments.api.models.products

import com.dodopayments.api.core.JsonValue
import com.dodopayments.api.core.jsonMapper
import com.dodopayments.api.models.creditentitlements.CbbOverageBehavior
import com.dodopayments.api.models.entitlements.EntitlementIntegrationType
import com.dodopayments.api.models.entitlements.FeatureType
import com.dodopayments.api.models.entitlements.IntegrationConfigResponse
import com.dodopayments.api.models.misc.Currency
import com.dodopayments.api.models.misc.Metadata
import com.dodopayments.api.models.misc.TaxCategory
import com.dodopayments.api.models.products.localizedprices.PricingMode
import com.dodopayments.api.models.subscriptions.TimeInterval
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ProductTest {

    @Test
    fun create() {
        val product =
            Product.builder()
                .brandId("brand_id")
                .businessId("business_id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .addCreditEntitlement(
                    CreditEntitlementMappingResponse.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .creditEntitlementId("credit_entitlement_id")
                        .creditEntitlementName("credit_entitlement_name")
                        .creditEntitlementUnit("credit_entitlement_unit")
                        .creditsAmount("credits_amount")
                        .overageBehavior(CbbOverageBehavior.FORGIVE_AT_RESET)
                        .overageEnabled(true)
                        .prorationBehavior(CbbProrationBehavior.PRORATE)
                        .rolloverEnabled(true)
                        .trialCreditsExpireAfterTrial(true)
                        .currency(Currency.AED)
                        .expiresAfterDays(0)
                        .lowBalanceThresholdPercent(0)
                        .maxRolloverCount(0)
                        .overageLimit("overage_limit")
                        .pricePerUnit("price_per_unit")
                        .rolloverPercentage(0)
                        .rolloverTimeframeCount(0)
                        .rolloverTimeframeInterval(TimeInterval.DAY)
                        .trialCredits("trial_credits")
                        .build()
                )
                .addEntitlement(
                    ProductEntitlementSummary.builder()
                        .id("id")
                        .integrationConfig(
                            IntegrationConfigResponse.FeatureFlagConfig.builder()
                                .featureId("feature_id")
                                .featureType(FeatureType.BOOLEAN)
                                .build()
                        )
                        .integrationType(EntitlementIntegrationType.DISCORD)
                        .name("name")
                        .description("description")
                        .build()
                )
                .isRecurring(true)
                .licenseKeyEnabled(true)
                .metadata(
                    Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .price(
                    Price.OneTimePrice.builder()
                        .currency(Currency.AED)
                        .discount(0L)
                        .price(0)
                        .payWhatYouWant(true)
                        .purchasingPowerParity(true)
                        .suggestedPrice(0)
                        .taxInclusive(true)
                        .build()
                )
                .productId("product_id")
                .taxCategory(TaxCategory.DIGITAL_PRODUCTS)
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .addAddon("string")
                .description("description")
                .digitalProductDelivery(
                    DigitalProductDelivery.builder()
                        .addFile(
                            DigitalProductDeliveryFile.builder()
                                .downloadUrl("download_url")
                                .expiresIn(0L)
                                .fileId("file_id")
                                .filename("filename")
                                .contentType("content_type")
                                .fileSize(0L)
                                .build()
                        )
                        .externalUrl("external_url")
                        .instructions("instructions")
                        .build()
                )
                .image("image")
                .licenseKeyActivationMessage("license_key_activation_message")
                .licenseKeyActivationsLimit(0)
                .licenseKeyDuration(
                    LicenseKeyDuration.builder().count(0).interval(TimeInterval.DAY).build()
                )
                .name("name")
                .pricingMode(PricingMode.BY_CURRENCY)
                .productCollectionId("product_collection_id")
                .build()

        assertThat(product.brandId()).isEqualTo("brand_id")
        assertThat(product.businessId()).isEqualTo("business_id")
        assertThat(product.createdAt()).isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(product.creditEntitlements())
            .containsExactly(
                CreditEntitlementMappingResponse.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .creditEntitlementId("credit_entitlement_id")
                    .creditEntitlementName("credit_entitlement_name")
                    .creditEntitlementUnit("credit_entitlement_unit")
                    .creditsAmount("credits_amount")
                    .overageBehavior(CbbOverageBehavior.FORGIVE_AT_RESET)
                    .overageEnabled(true)
                    .prorationBehavior(CbbProrationBehavior.PRORATE)
                    .rolloverEnabled(true)
                    .trialCreditsExpireAfterTrial(true)
                    .currency(Currency.AED)
                    .expiresAfterDays(0)
                    .lowBalanceThresholdPercent(0)
                    .maxRolloverCount(0)
                    .overageLimit("overage_limit")
                    .pricePerUnit("price_per_unit")
                    .rolloverPercentage(0)
                    .rolloverTimeframeCount(0)
                    .rolloverTimeframeInterval(TimeInterval.DAY)
                    .trialCredits("trial_credits")
                    .build()
            )
        assertThat(product.entitlements())
            .containsExactly(
                ProductEntitlementSummary.builder()
                    .id("id")
                    .integrationConfig(
                        IntegrationConfigResponse.FeatureFlagConfig.builder()
                            .featureId("feature_id")
                            .featureType(FeatureType.BOOLEAN)
                            .build()
                    )
                    .integrationType(EntitlementIntegrationType.DISCORD)
                    .name("name")
                    .description("description")
                    .build()
            )
        assertThat(product.isRecurring()).isEqualTo(true)
        assertThat(product.licenseKeyEnabled()).isEqualTo(true)
        assertThat(product.metadata())
            .isEqualTo(
                Metadata.builder().putAdditionalProperty("foo", JsonValue.from("string")).build()
            )
        assertThat(product.price())
            .isEqualTo(
                Price.ofOneTime(
                    Price.OneTimePrice.builder()
                        .currency(Currency.AED)
                        .discount(0L)
                        .price(0)
                        .payWhatYouWant(true)
                        .purchasingPowerParity(true)
                        .suggestedPrice(0)
                        .taxInclusive(true)
                        .build()
                )
            )
        assertThat(product.productId()).isEqualTo("product_id")
        assertThat(product.taxCategory()).isEqualTo(TaxCategory.DIGITAL_PRODUCTS)
        assertThat(product.updatedAt()).isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(product.addons()).containsExactly("string")
        assertThat(product.description()).isEqualTo("description")
        assertThat(product.digitalProductDelivery())
            .isEqualTo(
                DigitalProductDelivery.builder()
                    .addFile(
                        DigitalProductDeliveryFile.builder()
                            .downloadUrl("download_url")
                            .expiresIn(0L)
                            .fileId("file_id")
                            .filename("filename")
                            .contentType("content_type")
                            .fileSize(0L)
                            .build()
                    )
                    .externalUrl("external_url")
                    .instructions("instructions")
                    .build()
            )
        assertThat(product.image()).isEqualTo("image")
        assertThat(product.licenseKeyActivationMessage())
            .isEqualTo("license_key_activation_message")
        assertThat(product.licenseKeyActivationsLimit()).isEqualTo(0)
        assertThat(product.licenseKeyDuration())
            .isEqualTo(LicenseKeyDuration.builder().count(0).interval(TimeInterval.DAY).build())
        assertThat(product.name()).isEqualTo("name")
        assertThat(product.pricingMode()).isEqualTo(PricingMode.BY_CURRENCY)
        assertThat(product.productCollectionId()).isEqualTo("product_collection_id")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val product =
            Product.builder()
                .brandId("brand_id")
                .businessId("business_id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .addCreditEntitlement(
                    CreditEntitlementMappingResponse.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .creditEntitlementId("credit_entitlement_id")
                        .creditEntitlementName("credit_entitlement_name")
                        .creditEntitlementUnit("credit_entitlement_unit")
                        .creditsAmount("credits_amount")
                        .overageBehavior(CbbOverageBehavior.FORGIVE_AT_RESET)
                        .overageEnabled(true)
                        .prorationBehavior(CbbProrationBehavior.PRORATE)
                        .rolloverEnabled(true)
                        .trialCreditsExpireAfterTrial(true)
                        .currency(Currency.AED)
                        .expiresAfterDays(0)
                        .lowBalanceThresholdPercent(0)
                        .maxRolloverCount(0)
                        .overageLimit("overage_limit")
                        .pricePerUnit("price_per_unit")
                        .rolloverPercentage(0)
                        .rolloverTimeframeCount(0)
                        .rolloverTimeframeInterval(TimeInterval.DAY)
                        .trialCredits("trial_credits")
                        .build()
                )
                .addEntitlement(
                    ProductEntitlementSummary.builder()
                        .id("id")
                        .integrationConfig(
                            IntegrationConfigResponse.FeatureFlagConfig.builder()
                                .featureId("feature_id")
                                .featureType(FeatureType.BOOLEAN)
                                .build()
                        )
                        .integrationType(EntitlementIntegrationType.DISCORD)
                        .name("name")
                        .description("description")
                        .build()
                )
                .isRecurring(true)
                .licenseKeyEnabled(true)
                .metadata(
                    Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .price(
                    Price.OneTimePrice.builder()
                        .currency(Currency.AED)
                        .discount(0L)
                        .price(0)
                        .payWhatYouWant(true)
                        .purchasingPowerParity(true)
                        .suggestedPrice(0)
                        .taxInclusive(true)
                        .build()
                )
                .productId("product_id")
                .taxCategory(TaxCategory.DIGITAL_PRODUCTS)
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .addAddon("string")
                .description("description")
                .digitalProductDelivery(
                    DigitalProductDelivery.builder()
                        .addFile(
                            DigitalProductDeliveryFile.builder()
                                .downloadUrl("download_url")
                                .expiresIn(0L)
                                .fileId("file_id")
                                .filename("filename")
                                .contentType("content_type")
                                .fileSize(0L)
                                .build()
                        )
                        .externalUrl("external_url")
                        .instructions("instructions")
                        .build()
                )
                .image("image")
                .licenseKeyActivationMessage("license_key_activation_message")
                .licenseKeyActivationsLimit(0)
                .licenseKeyDuration(
                    LicenseKeyDuration.builder().count(0).interval(TimeInterval.DAY).build()
                )
                .name("name")
                .pricingMode(PricingMode.BY_CURRENCY)
                .productCollectionId("product_collection_id")
                .build()

        val roundtrippedProduct =
            jsonMapper.readValue(jsonMapper.writeValueAsString(product), jacksonTypeRef<Product>())

        assertThat(roundtrippedProduct).isEqualTo(product)
    }
}
