// File generated from our OpenAPI spec by Stainless.

package com.dodopayments.api.models.moderation

import com.dodopayments.api.core.jsonMapper
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ModerationScreenResponseTest {

    @Test
    fun create() {
        val moderationScreenResponse =
            ModerationScreenResponse.builder()
                .categories(
                    ModerationCategoryScores.builder()
                        .childSexualExploitation(0.0)
                        .defamation(0.0)
                        .hate(0.0)
                        .indiscriminateWeapons(0.0)
                        .intellectualProperty(0.0)
                        .livingArtistStyle(0.0)
                        .minorCodedLanguage(0.0)
                        .nonConsensualIntimateImagery(0.0)
                        .nonViolentCrimes(0.0)
                        .privacy(0.0)
                        .promptInjection(0.0)
                        .realPersonLikeness(0.0)
                        .sexRelatedCrimes(0.0)
                        .sexualContent(0.0)
                        .specializedAdvice(0.0)
                        .suicideAndSelfHarm(0.0)
                        .violentCrimes(0.0)
                        .build()
                )
                .compoundTriggered(true)
                .decision(ModerationDecision.ALLOW)
                .latencyMs(0L)
                .normalizedApplied(true)
                .addNote("string")
                .passes(0L)
                .provenance(
                    ModerationCategoryProvenance.builder()
                        .childSexualExploitation(ModerationProvenance.TARGETED)
                        .defamation(ModerationProvenance.TARGETED)
                        .hate(ModerationProvenance.TARGETED)
                        .indiscriminateWeapons(ModerationProvenance.TARGETED)
                        .intellectualProperty(ModerationProvenance.TARGETED)
                        .livingArtistStyle(ModerationProvenance.TARGETED)
                        .minorCodedLanguage(ModerationProvenance.TARGETED)
                        .nonConsensualIntimateImagery(ModerationProvenance.TARGETED)
                        .nonViolentCrimes(ModerationProvenance.TARGETED)
                        .privacy(ModerationProvenance.TARGETED)
                        .promptInjection(ModerationProvenance.TARGETED)
                        .realPersonLikeness(ModerationProvenance.TARGETED)
                        .sexRelatedCrimes(ModerationProvenance.TARGETED)
                        .sexualContent(ModerationProvenance.TARGETED)
                        .specializedAdvice(ModerationProvenance.TARGETED)
                        .suicideAndSelfHarm(ModerationProvenance.TARGETED)
                        .violentCrimes(ModerationProvenance.TARGETED)
                        .build()
                )
                .requestId("request_id")
                .addTriggered(ModerationCategory.VIOLENT_CRIMES)
                .build()

        assertThat(moderationScreenResponse.categories())
            .isEqualTo(
                ModerationCategoryScores.builder()
                    .childSexualExploitation(0.0)
                    .defamation(0.0)
                    .hate(0.0)
                    .indiscriminateWeapons(0.0)
                    .intellectualProperty(0.0)
                    .livingArtistStyle(0.0)
                    .minorCodedLanguage(0.0)
                    .nonConsensualIntimateImagery(0.0)
                    .nonViolentCrimes(0.0)
                    .privacy(0.0)
                    .promptInjection(0.0)
                    .realPersonLikeness(0.0)
                    .sexRelatedCrimes(0.0)
                    .sexualContent(0.0)
                    .specializedAdvice(0.0)
                    .suicideAndSelfHarm(0.0)
                    .violentCrimes(0.0)
                    .build()
            )
        assertThat(moderationScreenResponse.compoundTriggered()).isEqualTo(true)
        assertThat(moderationScreenResponse.decision()).isEqualTo(ModerationDecision.ALLOW)
        assertThat(moderationScreenResponse.latencyMs()).isEqualTo(0L)
        assertThat(moderationScreenResponse.normalizedApplied()).isEqualTo(true)
        assertThat(moderationScreenResponse.notes()).containsExactly("string")
        assertThat(moderationScreenResponse.passes()).isEqualTo(0L)
        assertThat(moderationScreenResponse.provenance())
            .isEqualTo(
                ModerationCategoryProvenance.builder()
                    .childSexualExploitation(ModerationProvenance.TARGETED)
                    .defamation(ModerationProvenance.TARGETED)
                    .hate(ModerationProvenance.TARGETED)
                    .indiscriminateWeapons(ModerationProvenance.TARGETED)
                    .intellectualProperty(ModerationProvenance.TARGETED)
                    .livingArtistStyle(ModerationProvenance.TARGETED)
                    .minorCodedLanguage(ModerationProvenance.TARGETED)
                    .nonConsensualIntimateImagery(ModerationProvenance.TARGETED)
                    .nonViolentCrimes(ModerationProvenance.TARGETED)
                    .privacy(ModerationProvenance.TARGETED)
                    .promptInjection(ModerationProvenance.TARGETED)
                    .realPersonLikeness(ModerationProvenance.TARGETED)
                    .sexRelatedCrimes(ModerationProvenance.TARGETED)
                    .sexualContent(ModerationProvenance.TARGETED)
                    .specializedAdvice(ModerationProvenance.TARGETED)
                    .suicideAndSelfHarm(ModerationProvenance.TARGETED)
                    .violentCrimes(ModerationProvenance.TARGETED)
                    .build()
            )
        assertThat(moderationScreenResponse.requestId()).isEqualTo("request_id")
        assertThat(moderationScreenResponse.triggered())
            .containsExactly(ModerationCategory.VIOLENT_CRIMES)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val moderationScreenResponse =
            ModerationScreenResponse.builder()
                .categories(
                    ModerationCategoryScores.builder()
                        .childSexualExploitation(0.0)
                        .defamation(0.0)
                        .hate(0.0)
                        .indiscriminateWeapons(0.0)
                        .intellectualProperty(0.0)
                        .livingArtistStyle(0.0)
                        .minorCodedLanguage(0.0)
                        .nonConsensualIntimateImagery(0.0)
                        .nonViolentCrimes(0.0)
                        .privacy(0.0)
                        .promptInjection(0.0)
                        .realPersonLikeness(0.0)
                        .sexRelatedCrimes(0.0)
                        .sexualContent(0.0)
                        .specializedAdvice(0.0)
                        .suicideAndSelfHarm(0.0)
                        .violentCrimes(0.0)
                        .build()
                )
                .compoundTriggered(true)
                .decision(ModerationDecision.ALLOW)
                .latencyMs(0L)
                .normalizedApplied(true)
                .addNote("string")
                .passes(0L)
                .provenance(
                    ModerationCategoryProvenance.builder()
                        .childSexualExploitation(ModerationProvenance.TARGETED)
                        .defamation(ModerationProvenance.TARGETED)
                        .hate(ModerationProvenance.TARGETED)
                        .indiscriminateWeapons(ModerationProvenance.TARGETED)
                        .intellectualProperty(ModerationProvenance.TARGETED)
                        .livingArtistStyle(ModerationProvenance.TARGETED)
                        .minorCodedLanguage(ModerationProvenance.TARGETED)
                        .nonConsensualIntimateImagery(ModerationProvenance.TARGETED)
                        .nonViolentCrimes(ModerationProvenance.TARGETED)
                        .privacy(ModerationProvenance.TARGETED)
                        .promptInjection(ModerationProvenance.TARGETED)
                        .realPersonLikeness(ModerationProvenance.TARGETED)
                        .sexRelatedCrimes(ModerationProvenance.TARGETED)
                        .sexualContent(ModerationProvenance.TARGETED)
                        .specializedAdvice(ModerationProvenance.TARGETED)
                        .suicideAndSelfHarm(ModerationProvenance.TARGETED)
                        .violentCrimes(ModerationProvenance.TARGETED)
                        .build()
                )
                .requestId("request_id")
                .addTriggered(ModerationCategory.VIOLENT_CRIMES)
                .build()

        val roundtrippedModerationScreenResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(moderationScreenResponse),
                jacksonTypeRef<ModerationScreenResponse>(),
            )

        assertThat(roundtrippedModerationScreenResponse).isEqualTo(moderationScreenResponse)
    }
}
