// File generated from our OpenAPI spec by Stainless.

package com.dodopayments.api.models.checkoutsessions

import com.dodopayments.api.core.jsonMapper
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CheckoutSessionCustomizationTest {

    @Test
    fun create() {
        val checkoutSessionCustomization =
            CheckoutSessionCustomization.builder()
                .forceLanguage("force_language")
                .showOnDemandTag(true)
                .showOrderDetails(true)
                .theme(CheckoutSessionCustomization.Theme.DARK)
                .themeConfig(
                    ThemeConfig.builder()
                        .dark(
                            ThemeModeConfig.builder()
                                .bgPrimary("bg_primary")
                                .bgSecondary("bg_secondary")
                                .borderPrimary("border_primary")
                                .borderSecondary("border_secondary")
                                .buttonPrimary("button_primary")
                                .buttonPrimaryHover("button_primary_hover")
                                .buttonSecondary("button_secondary")
                                .buttonSecondaryHover("button_secondary_hover")
                                .buttonTextPrimary("button_text_primary")
                                .buttonTextSecondary("button_text_secondary")
                                .inputFocusBorder("input_focus_border")
                                .textError("text_error")
                                .textPlaceholder("text_placeholder")
                                .textPrimary("text_primary")
                                .textSecondary("text_secondary")
                                .textSuccess("text_success")
                                .build()
                        )
                        .fontPrimaryUrl("font_primary_url")
                        .fontSecondaryUrl("font_secondary_url")
                        .fontSize(ThemeConfig.FontSize.XS)
                        .fontWeight(ThemeConfig.FontWeight.NORMAL)
                        .light(
                            ThemeModeConfig.builder()
                                .bgPrimary("bg_primary")
                                .bgSecondary("bg_secondary")
                                .borderPrimary("border_primary")
                                .borderSecondary("border_secondary")
                                .buttonPrimary("button_primary")
                                .buttonPrimaryHover("button_primary_hover")
                                .buttonSecondary("button_secondary")
                                .buttonSecondaryHover("button_secondary_hover")
                                .buttonTextPrimary("button_text_primary")
                                .buttonTextSecondary("button_text_secondary")
                                .inputFocusBorder("input_focus_border")
                                .textError("text_error")
                                .textPlaceholder("text_placeholder")
                                .textPrimary("text_primary")
                                .textSecondary("text_secondary")
                                .textSuccess("text_success")
                                .build()
                        )
                        .payButtonText("pay_button_text")
                        .radius("radius")
                        .build()
                )
                .build()

        assertThat(checkoutSessionCustomization.forceLanguage()).isEqualTo("force_language")
        assertThat(checkoutSessionCustomization.showOnDemandTag()).isEqualTo(true)
        assertThat(checkoutSessionCustomization.showOrderDetails()).isEqualTo(true)
        assertThat(checkoutSessionCustomization.theme())
            .isEqualTo(CheckoutSessionCustomization.Theme.DARK)
        assertThat(checkoutSessionCustomization.themeConfig())
            .isEqualTo(
                ThemeConfig.builder()
                    .dark(
                        ThemeModeConfig.builder()
                            .bgPrimary("bg_primary")
                            .bgSecondary("bg_secondary")
                            .borderPrimary("border_primary")
                            .borderSecondary("border_secondary")
                            .buttonPrimary("button_primary")
                            .buttonPrimaryHover("button_primary_hover")
                            .buttonSecondary("button_secondary")
                            .buttonSecondaryHover("button_secondary_hover")
                            .buttonTextPrimary("button_text_primary")
                            .buttonTextSecondary("button_text_secondary")
                            .inputFocusBorder("input_focus_border")
                            .textError("text_error")
                            .textPlaceholder("text_placeholder")
                            .textPrimary("text_primary")
                            .textSecondary("text_secondary")
                            .textSuccess("text_success")
                            .build()
                    )
                    .fontPrimaryUrl("font_primary_url")
                    .fontSecondaryUrl("font_secondary_url")
                    .fontSize(ThemeConfig.FontSize.XS)
                    .fontWeight(ThemeConfig.FontWeight.NORMAL)
                    .light(
                        ThemeModeConfig.builder()
                            .bgPrimary("bg_primary")
                            .bgSecondary("bg_secondary")
                            .borderPrimary("border_primary")
                            .borderSecondary("border_secondary")
                            .buttonPrimary("button_primary")
                            .buttonPrimaryHover("button_primary_hover")
                            .buttonSecondary("button_secondary")
                            .buttonSecondaryHover("button_secondary_hover")
                            .buttonTextPrimary("button_text_primary")
                            .buttonTextSecondary("button_text_secondary")
                            .inputFocusBorder("input_focus_border")
                            .textError("text_error")
                            .textPlaceholder("text_placeholder")
                            .textPrimary("text_primary")
                            .textSecondary("text_secondary")
                            .textSuccess("text_success")
                            .build()
                    )
                    .payButtonText("pay_button_text")
                    .radius("radius")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val checkoutSessionCustomization =
            CheckoutSessionCustomization.builder()
                .forceLanguage("force_language")
                .showOnDemandTag(true)
                .showOrderDetails(true)
                .theme(CheckoutSessionCustomization.Theme.DARK)
                .themeConfig(
                    ThemeConfig.builder()
                        .dark(
                            ThemeModeConfig.builder()
                                .bgPrimary("bg_primary")
                                .bgSecondary("bg_secondary")
                                .borderPrimary("border_primary")
                                .borderSecondary("border_secondary")
                                .buttonPrimary("button_primary")
                                .buttonPrimaryHover("button_primary_hover")
                                .buttonSecondary("button_secondary")
                                .buttonSecondaryHover("button_secondary_hover")
                                .buttonTextPrimary("button_text_primary")
                                .buttonTextSecondary("button_text_secondary")
                                .inputFocusBorder("input_focus_border")
                                .textError("text_error")
                                .textPlaceholder("text_placeholder")
                                .textPrimary("text_primary")
                                .textSecondary("text_secondary")
                                .textSuccess("text_success")
                                .build()
                        )
                        .fontPrimaryUrl("font_primary_url")
                        .fontSecondaryUrl("font_secondary_url")
                        .fontSize(ThemeConfig.FontSize.XS)
                        .fontWeight(ThemeConfig.FontWeight.NORMAL)
                        .light(
                            ThemeModeConfig.builder()
                                .bgPrimary("bg_primary")
                                .bgSecondary("bg_secondary")
                                .borderPrimary("border_primary")
                                .borderSecondary("border_secondary")
                                .buttonPrimary("button_primary")
                                .buttonPrimaryHover("button_primary_hover")
                                .buttonSecondary("button_secondary")
                                .buttonSecondaryHover("button_secondary_hover")
                                .buttonTextPrimary("button_text_primary")
                                .buttonTextSecondary("button_text_secondary")
                                .inputFocusBorder("input_focus_border")
                                .textError("text_error")
                                .textPlaceholder("text_placeholder")
                                .textPrimary("text_primary")
                                .textSecondary("text_secondary")
                                .textSuccess("text_success")
                                .build()
                        )
                        .payButtonText("pay_button_text")
                        .radius("radius")
                        .build()
                )
                .build()

        val roundtrippedCheckoutSessionCustomization =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(checkoutSessionCustomization),
                jacksonTypeRef<CheckoutSessionCustomization>(),
            )

        assertThat(roundtrippedCheckoutSessionCustomization).isEqualTo(checkoutSessionCustomization)
    }
}
